local zombieTXD = engineLoadTXD("skins/z5.txd")
engineImportTXD(zombieTXD, 69)
local zombieDFF = engineLoadDFF("skins/z5.dff", 69)
engineReplaceModel(zombieDFF, 69)
local zombieTXD = engineLoadTXD("skins/z6.txd")
engineImportTXD(zombieTXD, 70)
local zombieDFF = engineLoadDFF("skins/z6.dff", 70)
engineReplaceModel(zombieDFF, 70)
local zombieTXD = engineLoadTXD("skins/z7.txd")
engineImportTXD(zombieTXD, 92)
local zombieDFF = engineLoadDFF("skins/z7.dff", 92)
engineReplaceModel(zombieDFF, 92)
local zombieTXD = engineLoadTXD("skins/z8.txd")
engineImportTXD(zombieTXD, 97)
local zombieDFF = engineLoadDFF("skins/z8.dff", 97)
engineReplaceModel(zombieDFF, 97)
local zombieTXD = engineLoadTXD("skins/z9.txd")
engineImportTXD(zombieTXD, 105)
local zombieDFF = engineLoadDFF("skins/z9.dff", 105)
engineReplaceModel(zombieDFF, 105)
local zombieTXD = engineLoadTXD("skins/z10.txd")
engineImportTXD(zombieTXD, 107)
local zombieDFF = engineLoadDFF("skins/z10.dff", 107)
engineReplaceModel(zombieDFF, 107)
local zombieTXD = engineLoadTXD("skins/z11.txd")
engineImportTXD(zombieTXD, 108)
local zombieDFF = engineLoadDFF("skins/z11.dff", 108)
engineReplaceModel(zombieDFF, 108)
local zombieTXD = engineLoadTXD("skins/z12.txd")
engineImportTXD(zombieTXD, 126)
local zombieDFF = engineLoadDFF("skins/z12.dff", 126)
engineReplaceModel(zombieDFF, 126)
local zombieTXD = engineLoadTXD("skins/z13.txd")
engineImportTXD(zombieTXD, 127)
local zombieDFF = engineLoadDFF("skins/z13.dff", 127)
engineReplaceModel(zombieDFF, 127)
local zombieTXD = engineLoadTXD("skins/z14.txd")
engineImportTXD(zombieTXD, 128)
local zombieDFF = engineLoadDFF("skins/z14.dff", 128)
engineReplaceModel(zombieDFF, 128)
local zombieTXD = engineLoadTXD("skins/z15.txd")
engineImportTXD(zombieTXD, 152)
local zombieDFF = engineLoadDFF("skins/z15.dff", 152)
engineReplaceModel(zombieDFF, 152)
local zombieTXD = engineLoadTXD("skins/z16.txd")
engineImportTXD(zombieTXD, 162)
local zombieDFF = engineLoadDFF("skins/z16.dff", 162)
engineReplaceModel(zombieDFF, 162)
local zombieTXD = engineLoadTXD("skins/z1.txd")
engineImportTXD(zombieTXD, 167)
local zombieDFF = engineLoadDFF("skins/z1.dff", 167)
engineReplaceModel(zombieDFF, 167)
local zombieTXD = engineLoadTXD("skins/z2.txd")
engineImportTXD(zombieTXD, 188)
local zombieDFF = engineLoadDFF("skins/z2.dff", 188)
engineReplaceModel(zombieDFF, 188)
local zombieTXD = engineLoadTXD("skins/z3.txd")
engineImportTXD(zombieTXD, 195)
local zombieDFF = engineLoadDFF("skins/z3.dff", 195)
engineReplaceModel(zombieDFF, 195)
local zombieTXD = engineLoadTXD("skins/z4.txd")
engineImportTXD(zombieTXD, 206)
local zombieDFF = engineLoadDFF("skins/z4.dff", 206)
engineReplaceModel(zombieDFF, 206)